# SQL DATA ANALYSIS

### Author:  Gordon Moenga

## Introduction

This project focuses on using SQL to analyze an e-commerce dataset and extract meaningful insights from order, customer, product, payment, and sales information.

The analysis demonstrates fundamental SQL skills including data extraction, filtering, sorting, grouping, and aggregation. The objective is to use SQL queries to identify patterns and trends that can support business decision-making.

## Project Objectives

The main objectives of this project are to:

1. Use SELECT queries to extract relevant information from the dataset.
2. Use WHERE to filter records based on specific conditions.
3. Use ORDER BY to sort and rank results.
4. Use GROUP BY to analyze data across different categories.
5. Apply basic aggregate functions including COUNT(), SUM(), and AVG().
6. Identify meaningful business insights from the query results.
7. Demonstrate practical application of SQL fundamentals to a real-world dataset.

### Import Libraries

In [1]:
import sqlite3
import pandas as pd

### Load the dataset

In [2]:
data = pd.read_csv('cleaned_dataset.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
 14  CalculatedTotal  1200 non-null   float64
 15  PriceDifference  1200 non-null   float64
dtypes: float64(4), int64(2), object(10)
memory usage: 150.1+ KB

In [4]:
# load the dataset into sql
connect = sqlite3.connect(":memory:")

data.to_sql(
    "data",
    connect,
    index=False
)

1200

## Basic Select Queries

In [5]:
# display all records
query1 = """
SELECT *
FROM data
"""
records = pd.read_sql_query(query1, connect)
records

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedTotal,PriceDifference
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10,0.000000e+00
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,302.70,0.000000e+00
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40,4.547474e-13
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19,0.000000e+00
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04,107.04,0.000000e+00
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No Coupon,Facebook,1325.06,1325.06,0.000000e+00
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68,873.68,0.000000e+00
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08,1050.08,0.000000e+00
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32,2242.32,0.000000e+00

In [6]:
# selecting columns with important info
query2 = """
SELECT
    OrderID,
    Date,
    Product,
    Quantity,
    UnitPrice,
    TotalPrice
FROM data
"""
pd.read_sql_query(query2, connect)

        OrderID        Date  Product  Quantity  UnitPrice  TotalPrice
0     ORD200000  2023-01-04  Monitor         5     570.62     2853.10
1     ORD200001  2024-08-23    Phone         2     151.35      302.70
2     ORD200002  2024-02-27   Tablet         5     550.68     2753.40
3     ORD200003  2023-10-15    Chair         1     273.19      273.19
4     ORD200004  2025-05-08  Printer         4     626.01     2504.04
...         ...         ...      ...       ...        ...         ...
1195  ORD201195  2024-06-20     Desk         1     107.04      107.04
1196  ORD201196  2024-03-04  Monitor         2     662.53     1325.06
1197  ORD201197  2023-07-13   Tablet         2     436.84      873.68
1198  ORD201198  2024-08-22    Chair         4     262.52     1050.08
1199  ORD201199  2023-06-11   Tablet         4     560.58     2242.32

[1200 rows x 6 columns]

In [7]:
# display customer and order information
query3 = """
SELECT 
    CustomerID,
    Product,
    Quantity,
    OrderStatus,
    TotalPrice
FROM data
"""
pd.read_sql_query(query3, connect)

     CustomerID  Product  Quantity OrderStatus  TotalPrice
0        C72649  Monitor         5     Shipped     2853.10
1        C75739    Phone         2     Shipped      302.70
2        C81728   Tablet         5   Cancelled     2753.40
3        C33540    Chair         1    Returned      273.19
4        C81840  Printer         4   Delivered     2504.04
...         ...      ...       ...         ...         ...
1195     C21126     Desk         1   Cancelled      107.04
1196     C20095  Monitor         2   Cancelled     1325.06
1197     C79674   Tablet         2   Delivered      873.68
1198     C64753    Chair         4   Cancelled     1050.08
1199     C57502   Tablet         4    Returned     2242.32

[1200 rows x 5 columns]

In [8]:
# display pricing information
query4 = """
SELECT
    Product,
    Quantity,
    UnitPrice,
    TotalPrice,
    CalculatedTotal,
    PriceDifference
FROM data;
"""

pd.read_sql_query(query4, connect)

,Product,Quantity,UnitPrice,TotalPrice,CalculatedTotal,PriceDifference
0,Monitor,5,570.62,2853.10,2853.10,0.000000e+00
1,Phone,2,151.35,302.70,302.70,0.000000e+00
2,Tablet,5,550.68,2753.40,2753.40,4.547474e-13
3,Chair,1,273.19,273.19,273.19,0.000000e+00
4,Printer,4,626.01,2504.04,2504.04,0.000000e+00
...,...,...,...,...,...,...
1195,Desk,1,107.04,107.04,107.04,0.000000e+00
1196,Monitor,2,662.53,1325.06,1325.06,0.000000e+00
1197,Tablet,2,436.84,873.68,873.68,0.000000e+00
1198,Chair,4,262.52,1050.08,1050.08,0.000000e+00
1199,Tablet,4,560.58,2242.32,2242.32,0.000000e+00

## WHERE and ORDER BY to filter data & sort data

In [9]:
# orders with quantity more than three
query5 = """
SELECT *
FROM data
WHERE Quantity > 3;
"""
pd.read_sql_query(query5, connect)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedTotal,PriceDifference
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10,0.000000e+00
1,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40,4.547474e-13
2,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04,0.000000e+00
3,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75,747.75,0.000000e+00
4,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52,2037.52,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,ORD201180,2023-10-31,C42235,Chair,4,298.36,722 Main St,Debit Card,Pending,TRK49379882,8,FREESHIP,Google,1193.44,1193.44,0.000000e+00
464,ORD201189,2024-08-17,C96136,Tablet,5,389.22,149 Main St,Cash,Cancelled,TRK60856682,7,No Coupon,Referral,1946.10,1946.10,-2.273737e-13
465,ORD201191,2025-02-10,C44148,Desk,4,376.43,809 Main St,Gift Card,Pending,TRK67872709,5,WINTER15,Instagram,1505.72,1505.72,0.000000e+00
466,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08,1050.08,0.000000e+00
467,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32,2242.32,0.000000e+00

In [10]:
# orders with more than 4 items in cart
query6 = """
SELECT
    OrderID,
    Product,
    Quantity,
    OrderStatus,
    ItemsInCart,
    TotalPrice
FROM data
WHERE ItemsInCart > 4
ORDER BY TotalPrice DESC;
"""
pd.read_sql_query(query6, connect)

       OrderID  Product  Quantity OrderStatus  ItemsInCart  TotalPrice
0    ORD200789   Tablet         5   Delivered           10     3456.40
1    ORD201122  Monitor         5    Returned            8     3390.95
2    ORD200632   Laptop         5   Delivered            7     3390.80
3    ORD200469    Chair         5   Cancelled            5     3384.90
4    ORD200328   Tablet         5   Cancelled            7     3370.20
..         ...      ...       ...         ...          ...         ...
781  ORD200760     Desk         1   Cancelled            5       39.56
782  ORD200776   Tablet         1    Returned            5       21.19
783  ORD200542   Tablet         1   Cancelled            6       17.98
784  ORD200863    Phone         1     Pending            5       14.06
785  ORD201161    Phone         1   Cancelled            6       11.39

[786 rows x 6 columns]

In [11]:
# display delivered orders and ones with totalprice > 1000, ordered by total price
query7 = """
SELECT
    OrderID,
    Product,
    Quantity,
    UnitPrice,
    TotalPrice
FROM data
WHERE 
    TotalPrice > 1000 AND 
    OrderStatus = "Delivered"
ORDER BY TotalPrice DESC;
"""
pd.read_sql_query(query7, connect)

      OrderID  Product  Quantity  UnitPrice  TotalPrice
0   ORD200789   Tablet         5     691.28     3456.40
1   ORD200632   Laptop         5     678.16     3390.80
2   ORD201065  Printer         5     666.80     3334.00
3   ORD200361  Printer         5     659.85     3299.25
4   ORD200837    Chair         5     655.55     3277.75
..        ...      ...       ...        ...         ...
86  ORD201116  Printer         2     531.49     1062.98
87  ORD201092   Laptop         5     209.20     1046.00
88  ORD200939   Laptop         2     521.40     1042.80
89  ORD201098  Monitor         4     255.86     1023.44
90  ORD200589   Laptop         2     500.80     1001.60

[91 rows x 5 columns]

In [12]:
# pricing difference table
difference_query = """
SELECT
    OrderId,
    Product,
    TotalPrice,
    CalculatedTotal,
    PriceDifference
FROM data
WHERE PriceDifference <> 0
ORDER BY ABS(PriceDifference) DESC;
"""
pricing_difference = pd.read_sql_query(difference_query, connect)
pricing_difference

       OrderID  Product  TotalPrice  CalculatedTotal  PriceDifference
0    ORD200002   Tablet     2753.40          2753.40     4.547474e-13
1    ORD200010   Tablet     3129.85          3129.85    -4.547474e-13
2    ORD200032   Tablet     2683.60          2683.60    -4.547474e-13
3    ORD200086  Printer     3215.15          3215.15     4.547474e-13
4    ORD200118  Printer     2513.55          2513.55     4.547474e-13
..         ...      ...         ...              ...              ...
129  ORD200671    Chair      253.70           253.70    -2.842171e-14
130  ORD200723     Desk      164.85           164.85    -2.842171e-14
131  ORD200980    Chair      208.95           208.95    -2.842171e-14
132  ORD200604    Chair       97.86            97.86     1.421085e-14
133  ORD200710   Laptop      107.70           107.70     1.421085e-14

[134 rows x 5 columns]

In [13]:
# display orders that used debitcard as payment method ordered by the items in cart
query7 = """
SELECT
    OrderID,
    Product,
    Quantity,
    UnitPrice,
    TotalPrice
FROM data
WHERE PaymentMethod = "Debit Card"
ORDER BY TotalPrice DESC;
"""
pd.read_sql_query(query7, connect)

       OrderID  Product  Quantity  UnitPrice  TotalPrice
0    ORD201065  Printer         5     666.80     3334.00
1    ORD201031    Phone         5     664.51     3322.55
2    ORD200463   Laptop         5     662.78     3313.90
3    ORD200221   Tablet         5     639.37     3196.85
4    ORD200296     Desk         5     638.80     3194.00
..         ...      ...       ...        ...         ...
227  ORD200714   Laptop         1      51.73       51.73
228  ORD200067  Printer         4      12.10       48.40
229  ORD200760     Desk         1      39.56       39.56
230  ORD200303   Tablet         1      30.54       30.54
231  ORD200336   Laptop         1      18.20       18.20

[232 rows x 5 columns]

In [14]:
# display highest value orders that were cancelled
query8 = """
SELECT 
    OrderID,
    Product,
    Quantity,
    TotalPrice
FROM data
WHERE OrderStatus = "Cancelled"
ORDER BY TotalPrice DESC;
"""
pd.read_sql_query(query8, connect)

       OrderID  Product  Quantity  TotalPrice
0    ORD200469    Chair         5     3384.90
1    ORD200328   Tablet         5     3370.20
2    ORD200527    Chair         5     3267.35
3    ORD200768   Tablet         5     3267.30
4    ORD200889  Monitor         5     3253.60
..         ...      ...       ...         ...
245  ORD200136   Laptop         1       44.35
246  ORD200760     Desk         1       39.56
247  ORD200488    Chair         1       36.65
248  ORD200542   Tablet         1       17.98
249  ORD201161    Phone         1       11.39

[250 rows x 4 columns]

## Basic Aggregation Functions

In [15]:
# dataset overview
query9 = """
SELECT
    COUNT(*) AS Total_Orders
FROM data;
"""
overview = pd.read_sql_query(query9, connect)
overview

   Total_Orders
0          1200

In [16]:
# remove duplicated in customer id and return unique number of customers
query10 = """
SELECT 
    COUNT(DISTINCT CustomerID) AS Unique_Customers
FROM data;
"""
pd.read_sql_query(query10, connect)

   Unique_Customers
0              1189

In [17]:
# display overall performance
performance_query = """
SELECT
    SUM(TotalPrice) AS Total_Revenue,
    AVG(TotalPrice) AS Average_Order_Value,
    SUM(Quantity) AS Total_Units_Sold
FROM data;
"""
overall_performance = pd.read_sql_query(performance_query, connect)
overall_performance

   Total_Revenue  Average_Order_Value  Total_Units_Sold
0     1264761.96            1053.9683              3535

In [18]:
# display product performance
query11 = """
SELECT
    Product,
    COUNT(*) AS Number_Of_Orders,
    SUM(Quantity) AS Units_Sold,
    SUM(TotalPrice) AS Revenue,
    AVG(TotalPrice) AS Average_Order_Value
FROM data
GROUP BY product
ORDER BY Revenue DESC;
"""
product_performance = pd.read_sql_query(query11, connect)
product_performance

   Product  Number_Of_Orders  Units_Sold    Revenue  Average_Order_Value
0    Chair               178         562  195620.11          1098.989382
1  Printer               181         542  195612.61          1080.732652
2   Laptop               173         535  192126.56          1110.558150
3   Tablet               179         497  186568.95          1042.284637
4  Monitor               163         480  175651.41          1077.616012
5     Desk               170         508  167459.93           985.058412
6    Phone               156         411  151722.39           972.579423

In [19]:
# display customer performance
query12 = """
SELECT
    CustomerId,
    COUNT(*) AS Number_Of_Orders,
    SUM(TotalPrice) AS Amount_Spent
FROM data
GROUP BY CustomerId
ORDER BY Amount_Spent DESC;
"""
customer_performance = pd.read_sql_query(query12, connect)
customer_performance

     CustomerID  Number_Of_Orders  Amount_Spent
0        C38840                 2       5723.23
1        C57276                 1       3456.40
2        C67260                 1       3390.80
3        C13877                 1       3384.90
4        C18404                 1       3370.20
...         ...               ...           ...
1184     C88174                 1         18.20
1185     C49726                 1         17.98
1186     C14983                 1         17.24
1187     C98276                 1         14.06
1188     C32570                 1         11.39

[1189 rows x 3 columns]

In [20]:
# Referral performance
referral_query = """
SELECT
    ReferralSource,
    COUNT(*) AS Number_Of_Orders,
    SUM(TotalPrice) AS Revenue,
    AVG(TotalPrice) AS Average_Order_Value
FROM data
GROUP BY ReferralSource
ORDER BY Revenue DESC;
"""
referral_performance = pd.read_sql_query(referral_query, connect)
referral_performance

  ReferralSource  Number_Of_Orders    Revenue  Average_Order_Value
0      Instagram               259  275285.45          1062.878185
1          Email               250  261808.55          1047.234200
2         Google               241  250441.48          1039.176266
3       Facebook               228  250410.90          1098.293421
4       Referral               222  226815.58          1021.691802

In [21]:
# performance for all payment methods
payment_query = """
SELECT
    PaymentMethod,
    COUNT(*) AS Number_Of_Orders,
    SUM(TotalPrice) AS Revenue,
    AVG(TotalPrice) AS Average_Order_Value
FROM data
GROUP BY PaymentMethod
ORDER BY Revenue DESC;
"""
payment_method_performance = pd.read_sql_query(payment_query, connect)
payment_method_performance

  PaymentMethod  Number_Of_Orders    Revenue  Average_Order_Value
0   Credit Card               234  263847.63          1127.553974
1        Online               258  262442.94          1017.220698
2          Cash               246  259786.29          1056.041829
3     Gift Card               230  246323.92          1070.973565
4    Debit Card               232  232361.18          1001.556810

In [22]:
# order status performance summary
query13 = """
SELECT
    OrderStatus,
    COUNT(*) AS Number_Of_Orders,
    SUM(TotalPrice) AS Revenue
FROM data
GROUP BY OrderStatus
ORDER BY Revenue DESC;
"""
order_status_performance = pd.read_sql_query(query13, connect)
order_status_performance

  OrderStatus  Number_Of_Orders    Revenue
0   Cancelled               250  276396.21
1     Pending               237  256328.15
2     Shipped               235  246159.58
3    Returned               247  243277.70
4   Delivered               231  242600.32

In [24]:
# Revenue generated by completed orders
query14 = """
SELECT
    Product,
    COUNT(*) AS Number_Of_Orders,
    SUM(TotalPrice) AS Revenue,
    AVG(TotalPrice) AS Average_Order_Revenue
FROM data
WHERE OrderStatus = "Delivered"
GROUP BY Product
ORDER BY Revenue DESC
"""
completed_orders_summary = pd.read_sql_query(query14, connect)
completed_orders_summary

   Product  Number_Of_Orders   Revenue  Average_Order_Revenue
0   Laptop                40  40714.43            1017.860750
1    Phone                38  40345.41            1061.721316
2  Printer                29  38054.73            1312.232069
3  Monitor                31  35999.62            1161.278065
4   Tablet                28  31794.52            1135.518571
5    Chair                33  31465.83             953.510000
6     Desk                32  24225.78             757.055625